### ISSUE TITLE
Added a requirements file

### ISSUE THREAD

**Issue by moose99** [HA6Bots/FESBSC-Development-GitHub#3]
I added a requirements file to help devs install what is needed (I meant to do this via PR but forgot, sorry).

General questions about running this:

1. Looks like this will be windows only due to the use of win32 modules?  Is that correct?
2. I'm using Python36 - is everyone else expected to be on Python3 also?
3. I'm not sure where the main entry point is?  Tried running it and it looks like fesbsc2.py has some indentation issues so it's having problems starting up.  Is this meant to run yet or is still work in progress?

thanks

**Comment by HA6Bots** [comment]
I am undergoing a code clean up at the moment now that we have the encryption code. After this hopefully the code should be easier to read and I will make the main entry point apparent.

We will eventually make the bot compatible on different OS but right now we need to work on the basics.
